#!/usr/bin/env node
// @effect-diagnostics nodeBuiltinImport:off - A build-time codegen script; it runs under plain Node before any Effect runtime exists.
/**
 * Regenerates `src/openbotIcons.generated.ts`, the one list of Phosphor icon
 * names both the OpenBot picker and the `OpenbotProjectIcon` contract accept.
 *
 * A name that only looks like an icon (`Telescope`) used to pass validation and
 * then render the fallback glyph, so the contract has to check membership, not
 * just shape. Contracts cannot depend on `@phosphor-icons/react`: it would put
 * ~5 MB of icon components on the server's dependency graph. So the names are
 * read from the copy installed for `apps/openbot` at build time and committed
 * as plain strings.
 *
 * Run after bumping `@phosphor-icons/react` or editing `ALIAS_ICON_MODULES`:
 *
 *     node packages/contracts/scripts/generate-openbot-icons.ts
 *
 * `apps/openbot`'s `iconCatalog.test.ts` compares this list against the modules
 * the bundler actually globs, so a bump that is not regenerated fails there
 * rather than silently shrinking the picker.
 *
 * @module scripts/generate-openbot-icons
 */
import * as NodeFS from "node:fs";
import * as NodePath from "node:path";

const REPOSITORY_ROOT = NodePath.join(import.meta.dirname, "..", "..", "..");

/** One `.es.js` module per icon; the file name is the icon's contract name. */
const ICON_MODULE_DIRECTORY = NodePath.join(
  REPOSITORY_ROOT,
  "apps",
  "openbot",
  "node_modules",
  "@phosphor-icons",
  "react",
  "dist",
  "csr",
);

/** Owns `ALIAS_ICON_MODULES`, the v1 names the loader still resolves. */
const ICON_LOADER_PATH = NodePath.join(
  REPOSITORY_ROOT,
  "apps",
  "openbot",
  "src",
  "components",
  "projectIconLoader.ts",
);

const GENERATED_MODULE_PATH = NodePath.join(
  import.meta.dirname,
  "..",
  "src",
  "openbotIcons.generated.ts",
);

const MODULE_SUFFIX = ".es.js";

function readModuleNames(): ReadonlyArray<string> {
  const names = NodeFS.readdirSync(ICON_MODULE_DIRECTORY)
    .filter((file) => file.endsWith(MODULE_SUFFIX))
    .map((file) => file.slice(0, -MODULE_SUFFIX.length));
  if (names.length === 0) {
    throw new Error(`No icon modules under ${ICON_MODULE_DIRECTORY}; did the package layout move?`);
  }
  return names;
}

/**
 * The deprecated v1 aliases have no module of their own, so they are read out
 * of the loader's own table rather than restated here. Parsing beats a second
 * copy: the loader stays the only place an alias is declared.
 */
function readAliasNames(): ReadonlyArray<string> {
  const source = NodeFS.readFileSync(ICON_LOADER_PATH, "utf8");
  const table = /ALIAS_ICON_MODULES[^{]*\{([^}]*)\}/.exec(source);
  const names = table
    ? [...table[1].matchAll(/^\s*([A-Z][A-Za-z0-9]*)\s*:/gm)].map((match) => match[1] as string)
    : [];
  if (names.length === 0) {
    throw new Error(`No ALIAS_ICON_MODULES entries found in ${ICON_LOADER_PATH}.`);
  }
  return names;
}

/**
 * Every icon name the app can render, sorted the way the picker lists them.
 * `Sparkle` is dropped because the product never offers an AI sparkle as a
 * project icon, and the picker excludes it too.
 */
function readOpenbotIconNames(): ReadonlyArray<string> {
  const names = new Set([...readModuleNames(), ...readAliasNames()]);
  return [...names]
    .filter((name) => !name.includes("Sparkle"))
    .sort((left, right) => left.localeCompare(right));
}

function renderOpenbotIconsModule(names: ReadonlyArray<string>): string {
  return `// Generated by packages/contracts/scripts/generate-openbot-icons.ts. Do not edit.
// Regenerate after bumping @phosphor-icons/react or editing ALIAS_ICON_MODULES:
//   node packages/contracts/scripts/generate-openbot-icons.ts

/**
 * Every Phosphor icon name OpenBot accepts, sorted. Names only: the contract
 * validates against this list and the picker lists it, while the icon
 * components themselves are loaded one chunk at a time by the app.
 */
export const OPENBOT_ICON_NAMES: ReadonlyArray<string> = [
${names.map((name) => `  ${JSON.stringify(name)},\n`).join("")}];
`;
}

if (import.meta.main) {
  NodeFS.writeFileSync(GENERATED_MODULE_PATH, renderOpenbotIconsModule(readOpenbotIconNames()));
  process.stdout.write(`Wrote ${GENERATED_MODULE_PATH}\n`);
}
