// Generated by apps/server/scripts/generate-openbot-skills.ts. Do not edit.
// Edit the SKILL.md files beside this module, then run:
//   node apps/server/scripts/generate-openbot-skills.ts

export const OPENBOT_SKILLS: ReadonlyArray<{ readonly name: string; readonly markdown: string }> = [
  {
    name: "onboard",
    markdown: `---
name: onboard
description: Set up OpenBot for someone by creating the projects and shared knowledge they actually need. Use when a person asks to be onboarded, asks for help getting started, or asks you to set up their projects.
---

# Onboard

Turn a conversation into a small, correct set of OpenBot projects and shared knowledge entries. Cover what the person actually works on, and stop there. This is not an exhaustive map of someone's life.

## Read what already exists first

Call \`openbot_list_projects\` and \`openbot_knowledge_list\` before anything else.

Treat what they return as already correct. Update an existing project or entry only when the new information belongs in it; leave the rest untouched. Never rewrite every returned entry to match a template. When a project or entry already covers a topic, edit it by its id and current revision instead of adding a near-duplicate. Re-running this skill must converge.

## Ask only what changes the outcome

Ask about what you cannot infer and what would change what you create:

- Which areas of their life or work deserve a project.
- Which of those you should act in, and which you should only track.
- Standing preferences that shape every reply: tone, working hours, what never to do without asking.

Skip any question already answered in this conversation or in material they gave you, and skip any whose answer would not change the result. Send the questions you do have as one round rather than interviewing one at a time.

Prefer the harness's structured question tool: \`AskUserQuestion\` in Claude Code, the native request-for-user-input in Codex. If your harness has neither, use \`openbot_ask_question\` when it appears in your tool list. Otherwise ask in an ordinary \`openbot_send_message\`.

## Gather context you already have access to

Look only where a project inventory plausibly lives, then stop:

- \`~/agent-workspace/registry.toml\`, if it exists.
- \`README.md\` at the root of a directory the person named.
- Notes files they pointed you at.

Any MCP servers or connections available to you (for example a tools gateway) may be used for context when relevant, but none is required; proceed with local files and the conversation otherwise.

Ask before reading anything else, and always before reading anything that looks private, credentialed, or unclear in ownership. Do not walk a home directory, open mail, or read a repository nobody mentioned.

## Propose only when the set is not yet agreed

If the person has already reviewed the set they want, create it. Do not ask again.

Otherwise send a proposal with \`openbot_send_message\`: each project name with a one-line purpose and an icon guess, then the titles of the knowledge entries you would write. Adjust and re-propose if they push back.

## Create the set

- New project: \`openbot_create_project\` with a stable \`clientRequestId\` such as \`onboard:garden-planner\`, the name, a Phosphor icon name, and an \`instructions\` body carrying the standing preferences for that project.
- Existing project: \`openbot_update_project\` with its \`projectId\` and the \`revision\` from \`openbot_list_projects\`.
- New knowledge: \`openbot_knowledge_write\` with a title, a Markdown body, and \`projectIds\` linking it to the projects it is relevant to.
- Existing knowledge: \`openbot_knowledge_read\`, merge into the body you read, then \`openbot_knowledge_write\` with that \`knowledgeId\` and \`expectedRevision\`.

Never store secrets, credentials, or anything the person asked you to keep out of durable storage.

Create no routines. Onboarding sets up structure; scheduled work is a separate, explicit decision.

## Close with a summary

Send one last \`openbot_send_message\`: what you created, what you updated, what you skipped and why, and what they can ask for next.

## Example

Someone wants help with a vegetable patch, a book club, and moving house.

Projects:

- \`Garden planner\`, icon \`Plant\`, instructions "Southern-hemisphere seasons. Prefer low-effort suggestions."
- \`Book club\`, icon \`BookOpen\`, instructions "Meetings are monthly. Keep summaries under 200 words."
- \`House move\`, icon \`Package\`, instructions "Ask before contacting anyone."

Knowledge:

- "Garden bed layout", linked to \`Garden planner\`: four raised beds, full sun until 2pm, clay soil.
- "Book club cadence", linked to \`Book club\`: six members, first Tuesday, rotating host.

Everything above is invented. Write down the person's real answers and never these placeholders.
`,
  },
  {
    name: "import-grok",
    markdown: `---
name: import-grok
description: Import personal Grok bots into OpenBot projects, shared knowledge, and disabled routines. Use when a person asks to bring their Grok bots, their Grok memory, or a Grok export into OpenBot.
---

# Import Grok bots

Move a person's Grok bots into OpenBot without inventing anything and without touching the source.

## Locate the source

Ask where the export is. Do not assume a host, a path, or that one exists. Accept either:

- a local export directory the person names, or
- an SSH host and path the person gives you.

If they do not know where it is, say what you would need and stop. Never guess a hostname and never scan for one.

The source is read-only for the whole import. Never write to it, move it, or clean it up.

## Confirm the layout before mapping anything

Each personal bot usually has its own directory containing a profile file with the bot's name, description and system prompt, a memory or profile Markdown file, and an automations folder holding one JSON file per routine. Group bots normally carry an extra group membership file.

That is the common shape, not a promise. Open the actual files, confirm what is there, and report what you found before importing. Where a field is missing or shaped differently, follow the files, not this document.

## Map

| Grok                      | OpenBot                                                                                                             |
| ------------------------- | ------------------------------------------------------------------------------------------------------------------- |
| Bot                       | Project: name from the bot, \`instructions\` distilled from its system prompt, Phosphor icon guessed from its subject |
| Memory or knowledge entry | Knowledge entry via \`openbot_knowledge_write\`, linked to that bot's project                                         |
| Automation or routine     | \`schedule_task\` with \`enabled: false\` and \`deliveryMode: "queue"\`, targeting the project's main chat thread         |
| Transcript                | Skipped entirely                                                                                                    |

Distil, do not paste. A Grok system prompt usually mixes real standing preferences with Grok-specific scaffolding; keep the preferences and drop the scaffolding.

End every imported knowledge body with a provenance line:

\`\`\`
Source: Grok bot Garden Helper, imported 2026-01-15
\`\`\`

## Carry schedules across verbatim

A source routine normally carries a 5-field cron expression and the time zone of the host it ran on, often \`UTC\`. \`schedule_task\` takes \`{ type: "cron", expression, timeZone }\` with an IANA zone alongside \`interval\` and \`fixed_time\`, so a cron routine imports as a cron routine.

- Use the source time zone exactly as written. Never translate the expression into local time, and never approximate a cron as \`fixed_time\`.
- Make the prompt's first line: \`Imported from Grok bot <name> (source schedule: <cron> <tz>)\`.
- If the source uses a 6- or 7-field cron, or a schedule that is not cron at all, do not guess an equivalent. Leave it disabled, put the original schedule text in the prompt, and list it as "needs review".

## Import every routine disabled

Every imported routine gets \`enabled: false\`, without exception. An import must never start doing scheduled work the person has not re-approved. Tell them which routines are waiting and where to enable them.

## Flag group-chat bots instead of importing them

Source metadata normally marks whether a bot belonged to a group chat rather than to this person alone. When it does, or when membership is not clearly just this person, do not import it. Flag it and let them decide. A group bot's memory can hold other people's information, and it is not yours to copy.

## Make re-runs converge

Before creating anything, call \`openbot_list_projects\` and \`openbot_knowledge_list\`, then match by project name and knowledge title:

- Match found: update it, with \`openbot_update_project\`, or \`openbot_knowledge_read\` followed by \`openbot_knowledge_write\` carrying the id and revision.
- No match: create it with a \`clientRequestId\` derived from the source item, such as \`grok-import:garden-helper\`.

Running the import twice must leave exactly the same projects, entries, and routines.

## Finish with a table

Send one \`openbot_send_message\` listing every source item and its outcome:

| Item                                  | Type       | Outcome                                                    |
| ------------------------------------- | ---------- | ---------------------------------------------------------- |
| Garden Helper                         | bot        | Imported as project "Garden Helper"                        |
| Garden Helper / soil notes            | memory     | Imported as knowledge "Soil and beds"                      |
| Garden Helper / weekly watering check | routine    | Imported disabled as cron \`0 7 * * 1\` UTC                  |
| Garden Helper / hourly sweep          | routine    | Needs review: 6-field cron \`0 */30 * * * *\`, left disabled |
| Trivia Night                          | bot        | Flagged: group chat, membership unclear                    |
| Garden Helper / 412 messages          | transcript | Skipped                                                    |

Those rows are placeholders. Report the real source items and never invent one.
`,
  },
];
