#!/usr/bin/env node
// @effect-diagnostics nodeBuiltinImport:off - A build-time codegen script; it runs under plain Node before any Effect runtime exists.
/**
 * Embeds the OpenBot `SKILL.md` files into `src/openbot/skills/generated.ts`.
 *
 * The Markdown stays the source of truth so a skill reviews like every other
 * skill in the repo, but `dist/bin.mjs` ships one file and cannot read siblings
 * that were never bundled. String literals bundle for free, so the server reads
 * the generated module instead of the disk.
 *
 * Run after editing any `SKILL.md`:
 *
 *     node apps/server/scripts/generate-openbot-skills.ts
 *
 * `OpenbotSkills.test.ts` regenerates in memory and fails when the checked-in
 * module has drifted, so the two cannot disagree.
 *
 * @module scripts/generate-openbot-skills
 */
import * as NodeFS from "node:fs";
import * as NodePath from "node:path";

/** The shipped skills, in the order they are written into a workspace. */
export const OPENBOT_SKILL_NAMES = ["onboard", "import-grok"] as const;

export const SKILLS_DIRECTORY = NodePath.join(
  import.meta.dirname,
  "..",
  "src",
  "openbot",
  "skills",
);
export const GENERATED_MODULE_PATH = NodePath.join(SKILLS_DIRECTORY, "generated.ts");

export interface OpenbotSkillSource {
  readonly name: string;
  readonly markdown: string;
}

export function readOpenbotSkillSources(): ReadonlyArray<OpenbotSkillSource> {
  return OPENBOT_SKILL_NAMES.map((name) => ({
    name,
    markdown: NodeFS.readFileSync(NodePath.join(SKILLS_DIRECTORY, name, "SKILL.md"), "utf8"),
  }));
}

/**
 * Markdown goes in as a template literal so the generated module still reads
 * and diffs like prose. Only the three sequences that would end the literal or
 * start an interpolation are escaped.
 */
const toTemplateLiteral = (markdown: string) =>
  `\`${markdown.replaceAll("\\", "\\\\").replaceAll("`", "\\`").replaceAll("${", "\\${")}\``;

export function renderOpenbotSkillsModule(skills: ReadonlyArray<OpenbotSkillSource>): string {
  const entries = skills
    .map(
      (skill) =>
        `  {\n    name: ${JSON.stringify(skill.name)},\n    markdown: ${toTemplateLiteral(skill.markdown)},\n  },\n`,
    )
    .join("");
  return `// Generated by apps/server/scripts/generate-openbot-skills.ts. Do not edit.
// Edit the SKILL.md files beside this module, then run:
//   node apps/server/scripts/generate-openbot-skills.ts

export const OPENBOT_SKILLS: ReadonlyArray<{ readonly name: string; readonly markdown: string }> = [
${entries}];
`;
}

// Guarded so the test can import the renderer without rewriting the module.
if (import.meta.main) {
  NodeFS.writeFileSync(GENERATED_MODULE_PATH, renderOpenbotSkillsModule(readOpenbotSkillSources()));
  process.stdout.write(`Wrote ${GENERATED_MODULE_PATH}\n`);
}
